[windows]
192.168.3.100  # Substitua pelo IP da sua máquina Windows 11

[windows:vars]
ansible_user=Suporte
ansible_password=@Grupocyber
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
