---
- name: Verificar se Chocolatey ja esta instalado
  ansible.windows.win_stat:
    path: C:\ProgramData\chocolatey\bin\choco.exe
  register: choco_instalado

- name: Bloco de Instalacao do Chocolatey
  when: not choco_instalado.stat.exists
  block:
    - name: Garantir que a pasta C:\Temp existe
      ansible.windows.win_file:
        path: C:\Temp
        state: directory

    - name: Baixar script oficial do Chocolatey para o disco
      ansible.windows.win_get_url:
        url: https://community.chocolatey.org/install.ps1
        dest: C:\Temp\install_choco.ps1

    - name: Executar script de instalacao localmente
      ansible.windows.win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        & C:\Temp\install_choco.ps1

    - name: Limpar o script da pasta Temp
      ansible.windows.win_file:
        path: C:\Temp\install_choco.ps1
        state: absent