---
- name: Baseline Windows 11 - Instalacao de Softwares
  hosts: windows
  gather_facts: no

  tasks:
    - name: Garantir que o Chocolatey esteja instalado
      chocolatey.chocolatey.win_chocolatey:
        name: chocolatey
        state: present

    - name: Garantir que o Google Chrome esteja instalado
      chocolatey.chocolatey.win_chocolatey:
        name: googlechrome
        state: present
